Repository WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache, pull requests merged in 2024-08, with the labels that each got.

#16 S05 features footer
  .DS_Store
  public/.DS_Store
  public/assets/.DS_Store
  public/assets/css/style.css
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#18 S04 view correctifs
  public/assets/css/cart/cart.css
  public/assets/css/cart/ordered.css
  public/assets/css/infos/about.css
  public/assets/css/product/product.css
  public/assets/css/stock/stock.css
  public/assets/images/leather-fabric.webp
  public/assets/images/leather-tool.webp
  public/assets/images/people-meeting.webp
  src/Controller/AboutController.php
  src/Controller/Auth/AuthController.php
  src/Controller/admin/CategorieController.php
  src/Controller/admin/ProductController.php
  src/Service/Logger.php
  src/View/Admin/Categorie/_form.html.twig
  src/View/Admin/Categorie/edit.html.twig
  src/View/Admin/Categorie/index.html.twig
  src/View/Admin/Product/_form.html.twig
  src/View/Admin/Product/edit.html.twig
  src/View/Admin/Product/index.html.twig
  src/View/Admin/User/index.html.twig
  src/View/Cart/index.html.twig
  src/View/Cart/ordered.html.twig
  src/View/Infos/index.html.twig
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/routes.php
Labels: REVIEWED

#19 S06 link order user
  public/assets/css/form.css
  src/Controller/AbstractController.php
  src/Controller/Auth/AccountController.php
  src/Controller/Auth/AuthController.php
  src/Controller/CartController.php
  src/Controller/admin/CategorieController.php
  src/Controller/admin/OrderitemController.php
  src/Controller/admin/ProductController.php
  src/Controller/admin/StockController.php
  src/Controller/admin/UserController.php
  src/Model/OrderitemManager.php
  src/Model/admin/StockManager.php
  src/Service/Logger.php
  src/Service/LoggerCategory.php
  src/Service/LoggerConnection.php
  src/Service/LoggerProduct.php
  src/View/Auth/edit_account.html.twig
  src/View/Auth/login.html.twig
  src/View/Auth/user_account.html.twig
  src/View/Home/index.html.twig
  src/View/layout_admin.html.twig
  src/View/layout_login.html.twig
Labels: REVIEWED

#23 S06 category
  .gitignore
  log/.gitkeep
  src/Controller/AbstractController.php
  src/Controller/AuthController.php
  src/Controller/CategoryController.php
  src/Model/ProductManager.php
  src/Model/admin/CategorieManager.php
  src/Trait/CategoriesGetter.php
  src/View/Category/index.html.twig
  src/View/Home/index.html.twig
  src/View/header.html.twig
  src/routes.php
Labels: REVIEWED

#21 S05 filter
  public/assets/images/uploads/imgtatoo2.png
  public/assets/js/filter.js
  src/View/Admin/User/index.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#24 S06 legal
  public/assets/css/infos/legal.css
  public/assets/css/style.css
  src/Controller/AuthController.php
  src/Controller/LegalController.php
  src/View/Legal/index.html.twig
  src/View/header.html.twig
  src/routes.php
Labels: REVIEWED

#26 ajout d'images
  database.sql
  public/assets/images/aiguille-cuir.webp
  public/assets/images/bobine-de-fil.webp
  public/assets/images/boucle-ceinture.webp
  public/assets/images/couteau-rotatif.webp
  public/assets/images/cuir-chevre.webp
  public/assets/images/hammer-tools.svg
  public/assets/images/jar.svg
  public/assets/images/leather.svg
  public/assets/images/marteau-rivoir.webp
  public/assets/images/mensshoe.svg
  public/assets/images/peau-vache.webp
  public/assets/images/poincon.webp
  public/assets/images/rivets.webp
  public/assets/images/sewing-needle.svg
Labels: REVIEWED

#25 S06 design category
  public/assets/js/function.js
  src/Controller/CategoryController.php
  src/Controller/ProductController.php
  src/View/Category/index.html.twig
  src/View/Home/index.html.twig
  src/View/Product/index.html.twig
  src/View/header.html.twig
Labels: CHANGES REQUESTED

#27 S06 design category
  src/View/header.html.twig
Labels: REVIEWED

#29 fusion / suppression de controller
  database.sql
  src/Controller/AboutController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/LegalController.php
  src/Model/ItemManager.php
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/routes.php
  tests/controllers/HomeControllerTest.php.dist
  tests/models/ItemManagerTest.php.dist
Labels: REVIEWED

#30 S06 upgrade
  public/assets/css/infos/privacy.css
  public/assets/images/uploads/chaussures.png
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Model/admin/UserManager.php
  src/View/Admin/User/index.html.twig
  src/View/Privacy/index.html.twig
  src/View/header.html.twig
  src/routes.php
Labels: REVIEWED

#31 S06 sub category
  src/Controller/CategoryController.php
  src/Model/admin/CategorieManager.php
Labels: REVIEWED

#32 modif bdd
  database.sql
  src/View/Admin/User/index.html.twig
Labels: REVIEWED

#34 [design] footer link
  src/View/footer.html.twig
Labels: REVIEWED

#35 correctif
  src/View/Admin/Categorie/index.html.twig
  src/View/Admin/Product/index.html.twig
Labels: REVIEW REQUESTED, REVIEWED
